const PHN_CATALOG = {
  'F.VIT-90': {
    nombre: 'F. VIT CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Digestivo', 'Metabolismo'], beneficiosKey: ['digestivo','metabolismo'],
    img: 'imagen1.webp',
    precio: '$1,170',
    banners: ['banners/banner-FVIT-90.webp'],
    descripcion: 'PHN F.VIT cápsulas es un suplemento alimenticio a base de Semilla de trigo, Piña, Semilla de lino y Alga chlorella, formulado para coadyuvar en la regulación del metabolismo.',
    ingredientes: 'Hoja de Moringa (Moringa oleifera), Alga de Espirulina (Spirulina platensis), Semilla de Trigo (Triticum aestivum), Semilla de Guar (Cyamopsis tetragonoloba), Hoja de Té de Limón (Cymbopogon citratus), Hoja seca de Alfalfa (Medicago sativa), Semilla de Lino (Linum usitatissimum), Alga de Chlorella (Chlorella vulgaris), Pulpa de fruto de Piña (Ananas comosus), Hoja de Achicoria (Cichorium intybus var. foliosum), Semilla de Alcaravea (Carum carvi).',
    uso: 'PHN F.VIT cápsulas está desarrollado especialmente como auxiliar en el buen funcionamiento del sistema digestivo y coadyuvante en la regulación del metabolismo.',
    presentacion: 'Envase conteniendo 90 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 1 cápsula antes de dormir.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado para el consumo en menores de 18 años, durante el embarazo y lactancia. No se recomienda su consumo en personas con hipertensión, diabetes y problemas renales.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Potencializador metabólico que ayuda a tu cuerpo a quemar grasa de forma natural y mejora tu digestión desde la primera semana.',
    beneficiosList: ["Elimina la grasa que tu cuerpo no necesita", "Útil con problemas de estreñimiento", "Ayuda a la digestión", "Limpia el canal intestinal"],
  },
  'H-9': {
    nombre: 'H9 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Hepático'], beneficiosKey: ['hepatico'],
    img: 'imagen2.webp',
    precio: '$588',
    banners: ['banners/banner-H-9.webp'],
    descripcion: 'PHN H9 cápsulas es un suplemento alimenticio formulado como coadyuvante en el tratamiento de padecimientos hepáticos y biliares.',
    ingredientes: 'Hoja de Albahaca (Ocimum basilicum), Hoja de Moringa (Moringa oleifera), Fruto de Goji (Lycium barbarum), Alga de Espirulina (Spirulina platensis), Fruto sin pericarpio de Mangostán (Garcinia mangostana), Raíz tuberosa de Yuca (Manihot esculenta), Fruto sin semilla de Chicozapote (Manilkara zapota), Rizoma de Cúrcuma (Curcuma longa), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN H9 cápsulas está desarrollado para personas con problemas hepáticos y de vesícula.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Auxiliar en el tratamiento de padecimientos hepáticos y biliares. Depura y regenera tu hígado para que funcione como debe.',
    beneficiosList: ["Depura hígado y vesícula", "Reduce la inflamación hepática", "Nutre las células del hígado", "Mejora la digestión lenta"],
  },
  'G-6': {
    nombre: 'G6 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Digestivo', 'Gástrico'], beneficiosKey: ['digestivo','gastrico'],
    img: 'imagen3.webp',
    precio: '$588',
    banners: ['banners/banner-G-6.webp'],
    descripcion: 'PHN G6 cápsulas es un suplemento alimenticio formulado como auxiliar en el tratamiento de padecimientos gástricos.',
    ingredientes: 'Fruto sin semilla de Papaya (Carica papaya), Raíz tuberosa de Yuca (Manihot esculenta), Fruto sin pericarpio de Mangostán (Garcinia mangostana), Fruto de Goji (Lycium barbarum), Semilla de Guar (Cyamopsis tetragonoloba), Pulpa del fruto sin semilla de Mango africano (Irvingia gabonensis), Semilla de Nogal negro (Juglans nigra), Semilla de Alcaravea (Carum carvi), Hoja de Té de Limón (Cymbopogon citratus), Fruto y capullos florales de Alcaparro (Capparis spinosa).',
    uso: 'PHN G6 cápsulas está indicado para personas con problemas gástricos, tales como reflujo, gastritis y úlceras; apoyando también en la disminución de inflamación y acidez estomacal.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Auxiliar en el tratamiento de padecimientos gástricos. Calma tu estómago y repara la mucosa de forma natural.',
    beneficiosList: ["Alivia la gastritis y el reflujo", "Repara la mucosa gástrica", "Equilibra el pH del estómago", "Reduce la inflamación digestiva"],
  },
  'D-7': {
    nombre: 'D7 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Circulación', 'Colesterol'], beneficiosKey: ['circulacion','colesterol'],
    img: 'imagen4.webp',
    precio: '$588',
    banners: ['banners/banner-D-7.webp'],
    descripcion: 'PHN D7 cápsulas es un suplemento alimenticio formulado para coadyuvar en funciones depurativas y reguladoras del sistema linfático.',
    ingredientes: 'Flor de Lúpulo (Humulus lupulus), Rizoma de Cúrcuma (Curcuma longa), Alga de Chlorella (Chlorella vulgaris), Hoja de Moringa (Moringa oleifera), Pulpa del fruto sin semilla de Acai (Euterpe oleracea), Fruto de Maqui (Schisandra chinensis), Vitamina C (Ácido ascórbico), Vitamina E (α-Tocoferol), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN D7 cápsulas está desarrollado para auxiliar en la regulación de los niveles de colesterol y triglicéridos en la sangre, coadyuvando en la circulación sanguínea.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Depurativo y regulador del sistema linfático. Limpia tu sangre y mejora la circulación desde adentro.',
    beneficiosList: ["Mejora la circulación sanguínea", "Elimina las toxinas del cuerpo", "Disminuye niveles de triglicéridos y colesterol", "Reduce la concentración de grasa en sangre"],
  },
  'OV-12': {
    nombre: 'OV12 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Hormonal femenino'], beneficiosKey: ['hormonal'],
    img: 'imagen5.webp',
    precio: '$588',
    descripcion: 'PHN OV12 cápsulas es un suplemento alimenticio formulado como coadyuvante en la regulación hormonal de la mujer.',
    ingredientes: 'Estigma de la flor de Azafrán (Crocus sativus), Raíz tuberosa de Ñame (Dioscorea composita), Flor de Lúpulo (Humulus lupulus), Hoja de Estragón (Artemisia dracunculus), Hoja de Moringa (Moringa oleifera), Vitamina C (Ácido ascórbico), Vitamina E (α-tocoferol), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina B9 (Ácido fólico), Vitamina D (Calciferol), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN OV12 cápsulas está desarrollado para mujeres con padecimientos hormonales como la menopausia, cólicos o climaterio.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Regulador hormonal femenino natural. Equilibra tu ciclo, calma los cólicos y devuelve armonía a tu cuerpo de mujer.',
    beneficiosList: ["Regula el ciclo menstrual", "Reduce quistes ováricos", "Alivia cólicos y síndrome premenstrual", "Soporte en menopausia y climaterio"],
  },
  'A-10': {
    nombre: 'A10 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Articulaciones'], beneficiosKey: ['articulaciones'],
    img: 'imagen6.webp',
    precio: '$588',
    descripcion: 'PHN A10 cápsulas es un suplemento alimenticio a base de Cúrcuma y Nogal negro, formulado como coadyuvante en problemas articulares.',
    ingredientes: 'Rizoma de Cúrcuma (Curcuma longa), Flor de Lúpulo (Humulus lupulus), Semilla de Nogal negro (Juglans nigra), Flor y hoja de Malva (Malva sylvestris), Vitamina C (Ácido ascórbico), Vitamina E (α-tocoferol), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina A (Retinol), Vitamina K (Filoquinona), Vitamina D (Calciferol), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN A10 cápsulas está desarrollado como auxiliar en el buen funcionamiento y estado de las articulaciones, contribuyendo en el mantenimiento de la salud articular.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado para el consumo en niños menores de 12 años, durante embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Alivio natural para articulaciones. Reduce el dolor, fortalece tus articulaciones y baja el ácido úrico.',
    beneficiosList: ["Reduce el dolor de huesos", "Fortalece las articulaciones", "Disminuye el ácido úrico", "Auxiliar en artritis y reumatismo"],
  },
  'VC-1': {
    nombre: 'VC1 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Sistema inmune'], beneficiosKey: ['inmune'],
    img: 'imagen7.webp',
    precio: '$588',
    banners: ['banners/banner-VC-1.webp'],
    descripcion: 'PHN VC1 cápsulas es un suplemento alimenticio a base de Guanábana, Chirimoya y Vitamina C, formulado como auxiliar en el fortalecimiento del sistema inmune.',
    ingredientes: 'Fruto sin semilla de Guanábana (Annona muricata), Fruto sin semilla de Chirimoya (Annona squamosa), Vitamina C (Ácido ascórbico), Vitamina B1 (Tiamina), Vitamina D (Calciferol).',
    uso: 'PHN VC1 cápsulas está indicado en estados susceptibles de deficiencia de vitamina C, tiene efecto antioxidante y coadyuva en la prevención de algunas enfermedades respiratorias.',
    presentacion: 'Envase conteniendo 60 cápsulas de 450 mg c/u.',
    dosis: 'Tomar una cápsula por la mañana.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Fortalece tu sistema inmunológico con vitamina C natural y antioxidantes potentes para protegerte cada día.',
    beneficiosList: ["Fortalece el sistema inmune", "Previene enfermedades respiratorias", "Potente antioxidante", "Protege contra el daño celular"],
  },
  'EUK-7': {
    nombre: 'EUK7 Jarabe', tipo: 'Líquido', tipoKey: 'liquido',
    beneficios: ['Respiratorio', 'Sistema inmune'], beneficiosKey: ['respiratorio','inmune'],
    img: 'imagen8.webp',
    precio: '$588',
    banners: ['banners/banner-EUK-7.webp'],
    descripcion: 'PHN EUK7 es un suplemento alimenticio a base de miel virgen de abeja y Té Limón, formulado para auxiliar en padecimientos de las vías respiratorias.',
    ingredientes: 'Miel virgen de abeja (Apis mellifera), Hoja de Té de Limón (Cymbopogon citratus), Bulbo de Ajo (Allium sativum), Hoja de Moringa (Moringa oleifera), Hoja y tallo de Hinojo (Foeniculum vulgare), Hoja de Menta (Mentha spicata), Fruto de Sauco (Sambucus nigra), Vitamina C (Ácido ascórbico), Vitamina E (α-tocoferol), Vitamina A (Retinol).',
    uso: 'PHN EUK7 jarabe está desarrollado principalmente como coadyuvante en el tratamiento de la tos y en problemas de las amígdalas y bronquios inflamados.',
    presentacion: 'Envase conteniendo 250 ml.',
    dosis: 'Tomar 2 cucharadas soperas o 30 ml cada 3 horas. En niños menores de 12 años: 1 cucharada cafetera o 10 ml cada 3 horas.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Jarabe natural que alivia la tos, desinflama amígdalas y bronquios, y abre tus vías respiratorias.',
    beneficiosList: ["Alivia la tos seca y con flemas", "Desinflama amígdalas y bronquios", "Auxiliar en crisis asmáticas", "Abre las vías respiratorias"],
  },
  'N-7': {
    nombre: 'N7 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Sistema nervioso', 'Estrés'], beneficiosKey: ['nervioso','estres'],
    img: 'imagen9.webp',
    precio: '$588',
    banners: ['banners/banner-N-7.webp'],
    descripcion: 'PHN N7 cápsulas es un suplemento alimenticio formulado como auxiliar en el tratamiento de estados de ansiedad, angustia e insomnio.',
    ingredientes: 'Hoja de Té verde (Camellia sinensis), Semilla de Soya (Glycine max), Flor de Manzanilla (Matricaria chamomilla), Hoja de Moringa (Moringa oleifera), Hoja de Albahaca (Ocimum basilicum), Fruto de Maracuyá (Passiflora edulis), Fruto sin semilla de Chicozapote (Manilkara zapota), Ácido glutámico, Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN N7 cápsulas está indicado para personas con dolores de cabeza, nerviosismo, falta de memoria, estrés y migraña.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos. Niños menores de 12 años: 1 cápsula antes de cada alimento.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Equilibra tu sistema nervioso de forma natural. Calma la ansiedad, mejora el sueño y reduce el estrés.',
    beneficiosList: ["Regula el sistema nervioso", "Reduce problemas de insomnio", "Alivia migraña y estrés", "Mejora la concentración y memoria"],
  },
  'DB-6': {
    nombre: 'DB6 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Diabetes', 'Glucosa'], beneficiosKey: ['diabetes','glucosa'],
    img: 'imagen10.webp',
    precio: '$588',
    banners: ['banners/banner-DB-6.webp'],
    descripcion: 'PHN DB6 cápsulas es un suplemento alimenticio formulado como coadyuvante en padecimientos de páncreas y auxiliar en la regulación de los niveles de glucosa en la sangre.',
    ingredientes: 'Fruto de Manqui (Schisandra chinensis), Fruto sin pericarpio de Mangostán (Garcinia mangostana), Semilla de Achiote (Bixa orellana), Hoja y cogollo de Achicoria (Cichorium intybus var. foliosum), Hoja y cogollo de Endivia (Cichorium endivia), Alga de Chlorella (Chlorella vulgaris), Semilla de Nogal negro (Juglans nigra), Pulpa del Fruto sin semilla de Mango africano (Irvingia gabonensis), Vitamina C (Ácido ascórbico), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina).',
    uso: 'PHN DB6 cápsulas está desarrollado para coadyuvar en el tratamiento de la diabetes.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Regulador natural de azúcar en sangre. Estimula la producción de insulina y fortalece el páncreas.',
    beneficiosList: ["Disminuye los niveles de azúcar en sangre", "Estimula la producción de insulina natural", "Fortalece las funciones del páncreas", "Auxiliar en el tratamiento de diabetes"],
  },
  'R-12': {
    nombre: 'R12 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Renal'], beneficiosKey: ['renal'],
    img: 'imagen11.webp',
    precio: '$588',
    banners: ['banners/banner-R-12.webp'],
    descripcion: 'PHN R12 cápsulas es un suplemento alimenticio formulado como auxiliar en el tratamiento de padecimientos renales y vejiga.',
    ingredientes: 'Pulpa del fruto de Zapote blanco (Casimiroa edulis), Fruto de Sandía (Citrullus lanatus), Flor de Jamaica (Hibiscus sabdariffa), Fruto sin pericarpio de Mangostán (Garcinia mangostana), Fruto de Carambola (Averrhoa carambola), Vitamina C (Ácido ascórbico), Vitamina E (α-tocoferol), Vitamina D (Calciferol).',
    uso: 'PHN R12 cápsulas se indica para personas con problemas en los riñones, como inflamación y/o cálculos, que pueden causar dolores en la cintura y espalda baja.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Auxiliar renal que elimina la retención de líquidos, desinflama y alivia el malestar en riñones y espalda baja.',
    beneficiosList: ["Desinflamatorio renal", "Reduce la retención de líquidos", "Auxiliar en infecciones urinarias", "Disminuye el ácido úrico"],
  },
  'CR-7': {
    nombre: 'CR7 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Cardiovascular', 'Circulación'], beneficiosKey: ['cardiovascular','circulacion'],
    img: 'imagen12.webp',
    precio: '$588',
    banners: ['banners/banner-CR-7.webp'],
    descripcion: 'PHN CR7 es un suplemento alimenticio a base de Zapote blanco y Moringa, formulado para auxiliar en funciones del sistema cardiovascular, coadyuvando a la estabilidad de la presión arterial y el flujo sanguíneo.',
    ingredientes: 'Pulpa del Fruto de Zapote blanco (Casimiroa edulis), Semilla de Soya (Glycine max), Hoja de Moringa (Moringa oleifera), Flor de Lúpulo (Humulus lupulus), Fruto de Carambola (Averrhoa carambola), Pulpa del fruto sin semilla de Mango africano (Irvingia gabonensis), Vitamina B3 (Niacina), Vitamina B5 (Ácido pantoténico), Vitamina B2 (Riboflavina), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN CR7 cápsulas está desarrollado como auxiliar en padecimientos cardiovasculares.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, 3 veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Fortalece tu corazón y estabiliza la presión arterial de forma natural. Protección cardiovascular desde adentro.',
    beneficiosList: ["Regula la presión arterial", "Disminuye el colesterol", "Fortalece el sistema cardiovascular", "Reduce riesgos cardiovasculares"],
  },
  'FIBRA': {
    nombre: 'FIBRA F.VIT', tipo: 'Polvo', tipoKey: 'polvo',
    beneficios: ['Digestivo'], beneficiosKey: ['digestivo'],
    img: 'imagen13.webp',
    precio: '$975',
    banners: ['banners/banner-FIBRA.webp'],
    descripcion: 'PHN FIBRA F.VIT es un suplemento alimenticio a base de Semilla de Lino, Hoja de Moringa, Semilla de Chía, entre otros ingredientes, formulado para coadyuvar en el proceso digestivo.',
    ingredientes: 'Semilla de Lino (Linum usitatissimum), Hoja de Moringa (Moringa oleifera), Aceite de semilla de Ajonjolí (Sesamum indicum), Aceite de semilla de Girasol (Helianthus annuus), Semilla de Chía (Salvia hispanica), Fruto sin pericarpio de Mangostán (Garcinia mangostana), Semilla de Amaranto (Amaranthus caudatus), Semilla de Mostaza de la India (Brassica juncea), Fruto de Goji (Lycium barbarum), Alga de Espirulina (Spirulina platensis), Hoja de Albahaca (Ocimum basilicum), Fruto sin semilla de Chicozapote (Manilkara zapota), Semilla de Guar (Cyamopsis tetragonoloba), Raíz tuberosa de Yuca (Manihot esculenta), Pulpa de Fruto sin semilla de Mango africano (Irvingia gabonensis), Fruto de Ciruela pasa (Prunus domestica), Vitamina C (Ácido ascórbico), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina).',
    uso: 'PHN FIBRA F.VIT está desarrollado especialmente para complementar el aporte de fibra, y así auxiliar en el buen funcionamiento del sistema digestivo.',
    presentacion: 'Envase conteniendo 1 Kg de polvo.',
    dosis: 'Tomar 2 cucharadas en jugo de naranja o agua, 2 veces al día después de los alimentos.',
    contraindicaciones: 'No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Fibra natural que regula tu tránsito intestinal, alimenta tu microbiota y desinflamar tu abdomen.',
    beneficiosList: ["Regula el tránsito intestinal", "Alimenta la microbiota", "Reduce la inflamación abdominal", "Complementa el aporte de fibra diario"],
  },
  'LH': {
    nombre: 'F.VIT LH', tipo: 'Líquido', tipoKey: 'liquido',
    beneficios: ['Hepático'], beneficiosKey: ['hepatico'],
    img: 'imagen14.webp',
    precio: '$1,000',
    banners: ['banners/banner-LH.webp'],
    descripcion: 'PHN F.VIT LH es un suplemento alimenticio a base de Aceite de Olivo Extra Virgen y plantas, formulado como coadyuvante en el proceso digestivo.',
    ingredientes: 'Aceite de Olivo Extra Virgen, Hierba dulce, Raíz de Hidrastis, Vitamina E, Vitamina A.',
    uso: 'PHN F.VIT LH está desarrollado particularmente como auxiliar en padecimientos hepáticos y biliares.',
    presentacion: 'Caja contenida con dos frascos de 120 mL c/u.',
    dosis: 'Frasco N°1: tomar por la mañana con jugo de toronja, piña o naranja. Frasco N°2: tomar por la tarde con jugo de toronja, piña o naranja.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, durante el embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Depurador hepático natural. Limpia y activa tu hígado — el órgano que dirige la quema de grasa y la desintoxicación.',
    beneficiosList: ["Depura y activa el hígado", "Auxiliar en hígado graso", "Protege y regenera el tejido hepático", "Mejora la función biliar"],
  },
  'RGC-16': {
    nombre: 'RGC16 1L', tipo: 'Líquido', tipoKey: 'liquido',
    beneficios: ['Energía', 'Antioxidante'], beneficiosKey: ['energia','antioxidante'],
    img: 'imagen15.webp',
    precio: '$1,000',
    banners: ['banners/banner-RGC-16.webp'],
    descripcion: 'PHN RGC-16 es un suplemento alimenticio formulado como coadyuvante en el proceso de la regeneración celular, potenciador del sistema linfático y función antioxidante.',
    ingredientes: 'Fruto de Noni (Morinda citrifolia), Semilla de trigo (Triticum aestivum), Hoja de Moringa (Moringa oleifera), Fruto de Uva (Vitis vinifera), Semilla de Soya (Glycine max), Raíz de Betabel (Beta vulgaris), Pulpa del Fruto sin semilla de Acai (Euterpe oleracea), Fruto de Goji (Lycium barbarum), Fruto de Acerola (Malpighia emarginata), Fruto de Frambuesa (Rubus idaeus), Fruto de Grosello (Ribes rubrum), Fruto sin semilla de Guaraná (Paullinia cupana), Hoja de Menta (Mentha spicata).',
    uso: 'PHN RGC-16 está desarrollado para auxiliar en el mantenimiento de la salud y la función corporal.',
    presentacion: 'Envase conteniendo 1 litro.',
    dosis: 'Tomar una copita o 50 ml cada 24 horas.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco. Una vez abierto, consérvese en refrigeración.',
  
    propiedades: 'Regenerador celular con 16 frutas y plantas. Potencia tu sistema linfático y actúa como antioxidante profundo.',
    beneficiosList: ["Regeneración celular profunda", "Potencia el sistema linfático", "Antioxidante de amplio espectro", "Fortalece el sistema inmunológico"],
  },
  'F.VIT-GEL': {
    nombre: 'F.VIT GEL', tipo: 'Gel', tipoKey: 'gel',
    beneficios: ['Piel'], beneficiosKey: ['piel'],
    img: 'imagen16.webp',
    precio: '$250',
    banners: ['banners/banner-FVIT-GEL.webp'],
    descripcion: 'PHN F.VIT gel es un producto tópico formulado como coadyuvante a la pérdida de elasticidad y tonificación de la piel.',
    ingredientes: 'Agua, alcohol, trietanolamina, glicerina, carbopol, extracto de toronja, extracto de alga marina, mentol, alcanfor, centella asiática, salicilato de metilo, colágeno, colorante, fenoxietanol, esencia de romero.',
    uso: 'PHN F.VIT gel está desarrollado para reafirmar y tonificar la piel, generar sensación de frescura y ayudar a mejorar la apariencia cutánea. Aplicar sobre la piel limpia y seca. Evitar el contacto con la cara, axilas, ingles, heridas sin cerrar y genitales.',
    presentacion: 'Tubo depresible conteniendo 250 g.',
    dosis: 'Uso tópico externo.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No aplicar durante el embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco, alejado de la luz directa del sol.',
  
    propiedades: 'Gel tonificante que reafirma tu piel, reduce tallas y destapa los poros para una piel renovada.',
    beneficiosList: ["Reduce tallas", "Exfolia y destapa los poros", "Restaura y tonifica la piel", "Sensación de frescura inmediata"],
  },
  'AVI-13': {
    nombre: 'AVI13 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Sistema inmune', 'Respiratorio'], beneficiosKey: ['inmune','respiratorio'],
    img: 'imagen17.webp',
    precio: '$588',
    banners: ['banners/banner-AVI-13.webp', 'banners/banner-AVI-13-liquido.webp'],
    descripcion: 'PHN AVI13 cápsulas es un suplemento alimenticio a base de Cúrcuma, Manzanilla y Sauco, formulado para coadyuvar en el refuerzo del sistema inmunológico.',
    ingredientes: 'Cúrcuma (Curcuma longa), Manzanilla (Matricaria chamomilla), Jengibre (Zingiber officinale), Sauco (Sambucus nigra), Vitamina C (Ácido ascórbico), Vitamina A (Retinol), Vitamina D (Calciferol).',
    uso: 'PHN AVI13 cápsulas está desarrollado especialmente como auxiliar en problemas respiratorios.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Refuerza tu sistema inmunológico y fortalece las vías respiratorias para protegerte de infecciones.',
    beneficiosList: ["Fortalece el sistema inmunológico", "Auxiliar en problemas respiratorios", "Refuerza las defensas naturales", "Protección contra infecciones"],
  },
  'F.VIT 6': {
    nombre: 'F.VIT 6 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Digestivo', 'Detox'], beneficiosKey: ['digestivo','detox'],
    img: 'imagen18.webp',
    precio: '$588',
    banners: ['banners/banner-FVIT-6.webp'],
    descripcion: 'PHN F.VIT 6 cápsulas es un suplemento alimenticio formulado como auxiliar en el tratamiento de problemas digestivos.',
    ingredientes: 'Carbón Activado, Cúrcuma (Curcuma longa), Jengibre (Zingiber officinale), Vitamina C (Ácido ascórbico), Vitamina E (α-Tocoferol), Vitamina B6 (Piridoxina), Vitamina B1 (Tiamina), Vitamina A (Retinol), Vitamina K (Filoquinona), Vitamina B12 (Cianocobalamina).',
    uso: 'PHN F.VIT 6 cápsulas es un eficaz apoyo para desintoxicar naturalmente el organismo, y coadyuvar en problemas de inflamación estomacal y regulación de los gases intestinales.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Desintoxicante natural a base de carbón activado. Limpia tu organismo de toxinas y reduce la inflamación estomacal.',
    beneficiosList: ["Desintoxica el cuerpo", "Antibiótico natural purificador de sangre", "Reduce inflamación estomacal", "Elimina gases intestinales"],
  },
  'VR-4': {
    nombre: 'VR4 CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Circulación'], beneficiosKey: ['circulacion'],
    img: 'imagen19.webp',
    precio: '$588',
    banners: ['banners/banner-VR-4.webp'],
    descripcion: 'PHN VR4 cápsulas es un suplemento alimenticio formulado como auxiliar en padecimientos causados por problemas circulatorios.',
    ingredientes: 'Extracto de chile (Capsicum annum), Hoja de Hamamelis (Hamamelis virginiana), Vitamina C (Ácido ascórbico), Vitamina E (α-tocoferol), Vitamina B6 (Piridoxina).',
    uso: 'PHN VR4 cápsulas está desarrollado para coadyuvar en la estimulación de la circulación sanguínea y en padecimientos circulatorios como las várices y arañitas vasculares.',
    presentacion: 'Envase conteniendo 100 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas, tres veces al día antes de los alimentos.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula. No está indicado en niños menores de 12 años, embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Mejora tu circulación y combate las várices desde adentro. Fortalece las paredes venosas y alivia la pesadez.',
    beneficiosList: ["Mejora la circulación sanguínea", "Previene y reduce las várices", "Calma los dolores de las piernas", "Fortalece las paredes venosas"],
  },
  'VR-4 GEL': {
    nombre: 'VR4 GEL', tipo: 'Gel', tipoKey: 'gel',
    beneficios: ['Circulación', 'Piel'], beneficiosKey: ['circulacion','piel'],
    img: 'imagen20.webp',
    precio: '$250',
    banners: ['banners/banner-VR4-GEL.webp', 'banners/banner-VR4-GEL-modelo.webp'],
    descripcion: 'PHN VR4 gel es un producto tópico formulado como auxiliar en padecimientos causados por problemas circulatorios.',
    ingredientes: 'Agua, alcohol, carbopol, extracto de chile (Capsicum annum), mentol, alcanfor, extracto de hamamelis (Hamamelis virginiana).',
    uso: 'PHN VR4 gel está desarrollado para coadyuvar en la estimulación de la circulación sanguínea, reafirmando y tonificando la piel, y en padecimientos circulatorios como las várices y arañitas vasculares. Aplicar sobre la piel de manera uniforme. Evitar el contacto con la cara, axilas, ingles, heridas sin cerrar y genitales.',
    presentacion: 'Tubo depresible conteniendo 250 g.',
    dosis: 'Uso tópico externo.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco, alejado de la luz directa del sol.',
  
    propiedades: 'Gel tópico que estimula la circulación en tus piernas, hidrata y regenera la piel visiblemente.',
    beneficiosList: ["Estimula la circulación local", "Reduce la apariencia de várices", "Hidrata y regenera la piel", "Alivio inmediato de pesadez"],
  },
  'DB-6 CREMA': {
    nombre: 'DB6 CREMA', tipo: 'Crema', tipoKey: 'crema',
    beneficios: ['Piel'], beneficiosKey: ['piel'],
    img: 'imagen21.webp',
    precio: '$300',
    banners: ['banners/banner-DB6-CREMA.webp', 'banners/banner-DB6-CREMA-modelo.webp'],
    descripcion: 'PHN DB6 crema es un producto tópico formulado como coadyuvante en la estimulación de la regeneración de la piel con problemas de resequedad extrema y agrietamiento.',
    ingredientes: 'Agua, glicerina, extracto de aloe vera, olivato de cetearilo, olivato de sorbitán, manteca de karité, aceite de germen de trigo, diazolidinil urea, yodopropinil, butilcarbamato.',
    uso: 'PHN DB6 crema está desarrollada para auxiliar en la prevención de la resequedad de la piel, proporcionando firmeza y suavidad de la superficie cutánea. Aplicar sobre la piel limpia y seca. Evitar el contacto con los ojos, heridas sin cerrar y genitales.',
    presentacion: 'Tubo depresible conteniendo 200 g.',
    dosis: 'Uso tópico externo.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco, alejado de la luz directa del sol.',
  
    propiedades: 'Crema regeneradora para piel con resequedad extrema. Cicatriza, hidrata y estimula la regeneración cutánea.',
    beneficiosList: ["Hidrata la piel reseca", "Cicatriza agrietamientos", "Estimula la regeneración de la piel", "Devuelve firmeza y suavidad"],
  },
  'KIT F. VIT MAX': {
    nombre: 'Kit F.VIT MAX', tipo: 'Kit', tipoKey: 'kit',
    beneficios: ['Metabolismo'], beneficiosKey: ['metabolismo'],
    img: 'imagen24.webp',
    precio: '$2,999',
    descripcion: 'Kit completo PHN F.VIT MAX, formulado para coadyuvar en la regulación del metabolismo y el bienestar general.',
    ingredientes: 'Combinación de suplementos PHN seleccionados.',
    uso: 'Kit diseñado para apoyar el metabolismo y la salud integral.',
    presentacion: 'Kit con presentaciones combinadas.',
    dosis: 'Seguir las indicaciones individuales de cada producto incluido en el kit.',
    contraindicaciones: 'Ver indicaciones individuales de cada producto.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'El paquete completo para transformar tu metabolismo. Combina los suplementos PHN más potentes en un solo kit.',
    beneficiosList: ["Regulación completa del metabolismo", "Depuración hepática profunda", "Desintoxicación del organismo", "Máximos resultados en conjunto"],
  },
  'HERGY SX': {
    nombre: 'HERGY SX CAPS', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Energía masculina'], beneficiosKey: ['energia'],
    img: 'imagen26.webp',
    precio: '$1,100',
    banners: ['banners/banner-HERGY-SX.webp'],
    descripcion: 'PHN HERGY SX cápsulas es un suplemento alimenticio a base de Damiana y Guaraná, formulado para mejorar el flujo sanguíneo y potenciar el rendimiento físico.',
    ingredientes: 'Hoja de Damiana (Turnera diffusa), Fruto de Uva (Vitis vinifera), Hoja de Moringa (Moringa oleifera), Raíz de Betabel (Beta vulgaris), Alga de Chlorella (Chlorella vulgaris), Semilla de Guaraná (Paullinia cupana), Vitamina C, Vitamina B3 (Niacinamida), Vitamina B5 (Ácido pantoténico), Vitamina B2 (Riboflavina), Vitamina B1 (Tiamina), Vitamina B6 (Piridoxina), Vitamina B8 (Biotina).',
    uso: 'PHN HERGY SX cápsulas está sugerido para potenciar la energía masculina y el vigor.',
    presentacion: 'Envase conteniendo 30 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 1 cápsula al día.',
    contraindicaciones: 'No está indicado para el consumo en menores de 18 años. No se recomienda en personas con hipertensión, enfermedades del corazón y problemas renales. No está indicado durante el embarazo y lactancia.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Suplemento masculino que eleva la vitalidad, mejora el flujo sanguíneo y potencia el rendimiento físico.',
    beneficiosList: ["Eleva los niveles de testosterona", "Mejora el flujo sanguíneo", "Aumenta la fertilidad", "Potencia el rendimiento físico"],
  },
  'COLAGENO': {
    nombre: 'Colágeno CLGN', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Piel', 'Cabello'], beneficiosKey: ['piel','cabello'],
    img: 'imagen27.webp',
    precio: '$250',
    descripcion: 'PHN CLGN cápsulas es un suplemento alimenticio a base de colágeno hidrolizado y ácido hialurónico que contribuye a la producción natural de colágeno para mantener la salud de la piel, cabello y uñas.',
    ingredientes: 'Colágeno hidrolizado, Ácido hialurónico, Cúrcuma (Curcuma longa), Tallo de Caléndula (Calendula officinalis), Parte aérea de Centella asiática (Centella asiatica), Biotina.',
    uso: 'PHN CLGN cápsulas está formulado para auxiliar en el mantenimiento de la salud de la piel, cabello y uñas.',
    presentacion: 'Envase conteniendo 60 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas al día.',
    contraindicaciones: 'No se recomienda en personas con alergia a la proteína animal.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Colágeno hidrolizado con ácido hialurónico y biotina. Nutre tu piel, cabello y uñas desde adentro.',
    beneficiosList: ["Mejora la elasticidad de la piel", "Fortalece cabello y uñas", "Estimula la producción de colágeno", "Rejuvenece desde adentro"],
  },
  'MINERALES': {
    nombre: 'CM Minerales', tipo: 'Cápsulas', tipoKey: 'capsulas',
    beneficios: ['Sistema nervioso', 'Energía'], beneficiosKey: ['nervioso','energia'],
    img: 'imagen28.webp',
    precio: '$250',
    banners: ['banners/banner-MINERALES.webp'],
    descripcion: 'PHN CM MINERALES cápsulas es un suplemento a base de Citrato de magnesio y vitamina C que coadyuva a la disminución de los niveles de cortisol, mejora la calidad del sueño, combate la fatiga y mejora la concentración.',
    ingredientes: 'Citrato de magnesio, Vitamina C (Ácido ascórbico), Té Limón (Cymbopogon citratus), Hoja de Moringa (Moringa oleifera).',
    uso: 'PHN CM MINERALES está desarrollado para ayudar a reducir el estrés y promover el sueño, así como facilitar la producción de energía en el cuerpo.',
    presentacion: 'Envase conteniendo 60 cápsulas de 450 mg c/u.',
    dosis: 'Tomar 2 cápsulas al día.',
    contraindicaciones: 'No se recomienda en personas con diarrea crónica. Precaución en personas con insuficiencia renal.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Citrato de magnesio con vitamina C. Reduce el estrés, mejora el sueño y combate la fatiga diaria.',
    beneficiosList: ["Reduce estrés y cortisol", "Mejora la calidad del sueño", "Combate la fatiga", "Mejora concentración y energía"],
  },
  'COLAGENO 80/20': {
    nombre: 'Colágeno 80/20', tipo: 'Crema', tipoKey: 'crema',
    beneficios: ['Piel', 'Cabello'], beneficiosKey: ['piel','cabello'],
    img: 'imagen30.webp',
    precio: '$300',
    banners: ['banners/banner-COLAGENO-8020.webp', 'banners/banner-COLAGENO-8020-modelo.webp'],
    descripcion: 'Suplemento de colágeno PHN en formulación 50/50, para el cuidado de la piel, cabello y uñas.',
    ingredientes: 'Colágeno hidrolizado, Ácido hialurónico, vitaminas y minerales.',
    uso: 'Auxiliar en el mantenimiento de la salud de la piel, cabello y uñas.',
    presentacion: 'Envase conteniendo crema de 250 g.',
    dosis: 'Consulte a su asesor naturista.',
    contraindicaciones: 'No se recomienda en personas con alergia a la proteína animal.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Gel de colágeno para uso diurno. Rejuvenece y protege tu piel durante el día con ácido hialurónico.',
    beneficiosList: ["Rejuvenece la piel de día", "Protege contra el daño solar", "Hidrata profundamente", "Mejora la elasticidad cutánea"],
  },
  'COLAGENO 50/50': {
    nombre: 'Colágeno 50/50', tipo: 'Crema', tipoKey: 'crema',
    beneficios: ['Piel', 'Cabello'], beneficiosKey: ['piel','cabello'],
    img: 'imagen29.webp',
    precio: '$300',
    banners: ['banners/banner-COLAGENO-5050.webp', 'banners/banner-COLAGENO-5050-modelo.webp'],
    descripcion: 'Suplemento de colágeno PHN en formulación 50/50, para el cuidado de la piel, cabello y uñas.',
    ingredientes: 'Colágeno hidrolizado, Ácido hialurónico, vitaminas y minerales.',
    uso: 'Auxiliar en el mantenimiento de la salud de la piel, cabello y uñas.',
    presentacion: 'Envase conteniendo crema de 250 g.',
    dosis: 'Consulte a su asesor naturista.',
    contraindicaciones: 'No se recomienda en personas con alergia a la proteína animal.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Gel de colágeno para uso nocturno. Regenera tu piel mientras duermes con colágeno hidrolizado.',
    beneficiosList: ["Regenera la piel de noche", "Reduce líneas de expresión", "Nutre profundamente", "Restaura la firmeza cutánea"],
  },
  'MASCARILLA': {
    nombre: 'Mascarilla PHN', tipo: 'Crema', tipoKey: 'crema',
    beneficios: ['Piel'], beneficiosKey: ['piel'],
    img: 'imagen31.webp',
    precio: '$300',
    banners: ['banners/banner-MASCARILLA.webp', 'banners/banner-MASCARILLA-modelo.webp'],
    descripcion: 'Mascarilla PHN, formulada para el cuidado y nutrición de la piel del rostro.',
    ingredientes: 'Ingredientes naturales seleccionados.',
    uso: 'Aplicar sobre la piel limpia del rostro. Dejar actuar según indicaciones del producto.',
    presentacion: 'Consulte presentación disponible.',
    dosis: 'Uso tópico externo.',
    contraindicaciones: 'Hipersensibilidad a los componentes de la fórmula.',
    almacenamiento: 'Manténgase a temperatura ambiente a no más de 30°C, en un lugar seco y fresco.',
  
    propiedades: 'Mascarilla exfoliante aclaradora. Elimina manchas, nutre y renueva la piel de tu rostro.',
    beneficiosList: ["Exfolia y aclara la piel", "Elimina manchas", "Nutre el rostro", "Renueva la apariencia de la piel"],
  },
};
